chore: use "docker.io/antora/antora:3.0.1" container for BuildAndDeploy
devfile/landing-page pull request #10
Opened 2022-02-04 14:51 UTC by themr0c

Signed-off-by: Fabrice Flore-Thébault <ffloreth@redhat.com>

Fix build. kameshsampath/antora-site-action@master action doesn't support Antora 3.

2022-02-08 13:08 UTC, themr0c commented
It seems GitHub doesn't allow changing container during a workflow.

It would be safer to build the docs in the docs repository, and only copy the build output in this repository.

2022-02-08 16:08 UTC, schultzp2020 commented
@themr0c Ill look at this today.

2022-02-08 16:22 UTC, schultzp2020 requested changes

2022-02-08 16:22 UTC, schultzp2020 commented on .github/workflows/BuildAndDeploy.yaml
> +          yarn add @antora/lunr-extension
I don't think this is necessary. If you run this command locally in `/docs`, the package will automatically be installed when `yarn install` is executed.

2022-02-22 04:38 UTC, schultzp2020 submitted a review, later dismissed

2022-02-22 08:21 UTC, themr0c commented
Thanks for the approval @schultzp2020. 

The merging is still blocked, we need actions from yourself or a maintainer:

* Clear the "1 change requested".
* Approve running workflows to clear: "First-time contributors need a maintainer to approve running workflows."

2022-02-22 08:22 UTC, themr0c commented
@schultzp2020 can you merge the pull request? (I can't)

2022-02-22 13:22 UTC, schultzp2020 approved these changes

2022-02-22 13:31 UTC, merged